name: Delete merged branch of the backport PRs
on: 
  pull_request:
    types:
      - closed
  
jobs:
  delete-branch:
    runs-on: ip-172-31-48-64
    if: startsWith(github.event.pull_request.head.ref,'backport/')
    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
